[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ga"
version = "0.1.0"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["ga"]
